baseURL: https://zablotchi.github.io
languageCode: en-us
defaultContentLanguage: en
title: Igor Zablotchi
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: \@ [igor.zablotchi@epfl.ch](mailto:igor.zablotchi@epfl.ch)  
    [Google Scholar](https://scholar.google.com/citations?user=D6k7TYoAAAAJ&hl=en)<br/>  
    [DBLP](https://dblp.uni-trier.de/pid/136/1097.html)<br/>
    [LinkedIn](https://www.linkedin.com/in/zablo/)
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css

menu:
  nav:
    - name: About
      url: /
      weight: 1
    - name: Publications
      url: /publications/
      weight: 2
    - name: CV
      url: /cv.pdf
      weight: 3
    - name: Blog
      url: /post/
      weight: 4


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
